import { Hono } from 'hono'
import { annualReviewService } from '../services/annual-reviews.service'
import { annualReviewMessages } from '../config/annual-reviews.messages'
import {
  listAnnualReviewsSchema,
  updateAnnualReviewSchema,
} from '../config/annual-reviews.schema'
import { successResponse } from '../../../utils/response'
import { errorHandler } from '../../../utils/error-handler'
import { authWithPermission } from '../../../middleware/auth.middleware'
import { PERMISSIONS } from '../../../config/permissions.constants'
import type { AppEnv } from '../../../types/hono.types'
import type {
  AnnualReviewListItem,
  AnnualReviewListResponse,
  MissingDateClient,
} from '../types/annual-reviews.types'

// Annual Review — the ASIC annual-review tracker for company clients.
//
// Rows are generated by the system from each client's incorporation date; a member
// can only change a row's status and notes. There is therefore no create or delete
// route. One permission (ANNUAL_REVIEW.ACCESS) gates every endpoint, and every read
// is firm-scoped inside the service.
export const annualReviewRoutes = new Hono<AppEnv>()

// GET /api/annual-reviews — the list. Defaults to the current Australian calendar
// year, and generates that year on its first request if the sweep has not yet run.
annualReviewRoutes.get('/', authWithPermission(PERMISSIONS.ANNUAL_REVIEW.ACCESS), async (c) => {
  try {
    const query = listAnnualReviewsSchema.parse(c.req.query())
    const result = await annualReviewService.list(c.get('user'), query)
    return successResponse<AnnualReviewListResponse>(c, annualReviewMessages.LIST_FETCHED, result)
  } catch (error) {
    return errorHandler(error, c)
  }
})

// GET /api/annual-reviews/missing-date — clients whose entity type has annual review
// enabled but who have no incorporation date on file, so no row could be generated.
// Declared before /:id so it is not swallowed by a param route.
annualReviewRoutes.get(
  '/missing-date',
  authWithPermission(PERMISSIONS.ANNUAL_REVIEW.ACCESS),
  async (c) => {
    try {
      const result = await annualReviewService.listMissingDate(c.get('user'))
      return successResponse<{ items: MissingDateClient[] }>(
        c,
        annualReviewMessages.MISSING_DATE_FETCHED,
        { items: result },
      )
    } catch (error) {
      return errorHandler(error, c)
    }
  },
)

// PATCH /api/annual-reviews/:id — status and/or notes. Nothing else is accepted.
annualReviewRoutes.patch(
  '/:id',
  authWithPermission(PERMISSIONS.ANNUAL_REVIEW.ACCESS),
  async (c) => {
    try {
      const body = updateAnnualReviewSchema.parse(await c.req.json())
      const result = await annualReviewService.update(c.req.param('id')!, body)
      return successResponse<AnnualReviewListItem>(c, annualReviewMessages.UPDATED, result)
    } catch (error) {
      return errorHandler(error, c)
    }
  },
)
