-- Table: annual_reviews
-- Purpose: one row per eligible client per calendar year, tracking that client's
--          ASIC annual review through the firm's process.
--
--          Rows are GENERATED BY THE SYSTEM from the client's incorporation date,
--          never created by a member. A member can only change `status` and `notes`;
--          everything else is derived and read-only in the UI.
--
--          Eligibility (enforced in the service, not here): the client is active and
--          not deleted, their entity type has annual_review_enabled = TRUE, and they
--          have an incorporation date on file.
--
--          NOTE this is a CALENDAR-year feature and is deliberately unrelated to the
--          `financial_years` master data. The ASIC annual review falls on the
--          company's own registration anniversary, not on the Australian 1 July -
--          30 June financial year.

CREATE TABLE IF NOT EXISTS annual_reviews (
    id TEXT PRIMARY KEY DEFAULT generate_ulid(),

    client_id TEXT NOT NULL REFERENCES tax_clients(id),

    -- Calendar year this review belongs to, e.g. 2026.
    year INT NOT NULL,

    -- The anniversary of the client's incorporation date in `year`.
    --
    -- STORED rather than computed on read, for two reasons: the list sorts and
    -- filters on it cheaply, and a later correction to the client's incorporation
    -- date does not silently rewrite history. The service applies corrections to the
    -- current year onward only.
    review_date DATE NOT NULL,

    -- Fixed lifecycle. Hardcoded here (not master data like work_statuses) because
    -- these three steps are the firm's whole process for an annual review. Any
    -- status may move to any other - there are deliberately no transition rules.
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'sent_to_client', 'done')),

    -- One free-text note per row, edited in place on the list.
    notes TEXT,

    -- Soft delete (finance app - records are retained, never hard-deleted). There is
    -- NO delete flow yet; the columns exist so one can be added cleanly later.
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- THE most important line in this feature. It is what makes generation idempotent:
-- the sweep can run any number of times, from any number of callers, and still
-- produce exactly one row per client per year. Every generation query relies on
-- ON CONFLICT against this index.
--
-- Deliberately NOT filtered on is_deleted: a soft-deleted row must still block a
-- duplicate, otherwise the next sweep would silently resurrect it as a new row.
CREATE UNIQUE INDEX idx_annual_reviews_client_year
    ON annual_reviews (client_id, year);

CREATE INDEX idx_annual_reviews_year        ON annual_reviews (year)        WHERE is_deleted = FALSE;
CREATE INDEX idx_annual_reviews_status      ON annual_reviews (status)      WHERE is_deleted = FALSE;
CREATE INDEX idx_annual_reviews_review_date ON annual_reviews (review_date) WHERE is_deleted = FALSE;

-- Trigger: Auto-update updated_at
CREATE TRIGGER set_updated_at_annual_reviews
    BEFORE UPDATE ON annual_reviews
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
